// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIPKJJBfnDoMx9z-iIu2OthrNc5_69uM',
    appId: '1:769317691071:web:4b8059e2f3d9f1cd17f00a',
    messagingSenderId: '769317691071',
    projectId: 'hero-2f27c',
    authDomain: 'hero-2f27c.firebaseapp.com',
    storageBucket: 'hero-2f27c.appspot.com',
    measurementId: 'G-S2EZWCDCF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGesQ05n5SzkAXQisrPZ005VpOdGDmVE',
    appId: '1:769317691071:android:e9895cc9a875576d17f00a',
    messagingSenderId: '769317691071',
    projectId: 'hero-2f27c',
    storageBucket: 'hero-2f27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGLm43lXq11A6XQw5ae6epZ7DlgC34bik',
    appId: '1:769317691071:ios:fc80e08d47777a1e17f00a',
    messagingSenderId: '769317691071',
    projectId: 'hero-2f27c',
    storageBucket: 'hero-2f27c.appspot.com',
    iosBundleId: 'com.topbusiness.hero',
  );
}
